<a href="https://colab.research.google.com/github/lalopezpa/AlgorithmsUN2022II/blob/main/Quiz6/Goup7_Quiz6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Group 7 Quiz 6</h1>

**Members**

*   Santiago Londoño
*   Juan Diego Cortes
*   Laura Camila López

In [ ]:
import pandas as pd  
  
# assign data of lists.  
data = {'LMA': [  190, 190, 190 ,180, 180, 180,  150, 150, 150,], 
        'SMA': [10,15,20,10,15,20,10,15,20] , 
        'R6M': [ 0.022921129874471136,  0.022921129874471136, 0.002725464656761541,  0.002982711567232112, 0.007488470794877115, -0.006186427327789371, -0.03258814858580423,  -0.054593696731885806, -0.045931471490532505], 
        'R2Y': [0.12194728584035042,  0.13148503895402341,  0.17299407070127473, 0.0935911041221862,  0.14662371205564328,0.16747069358712313, 0.035050852376308825 , 0.09321346209762313,  0.11777216660367848]}  
  

# Create DataFrame  
df = pd.DataFrame(data)  

df['AR'] = (df['R6M'] + df['R2Y'])/2

df = df.sort_values(by=['AR'], ascending=False)
  
df

   LMA  SMA       R6M       R2Y        AR
2  190   20  0.002725  0.172994  0.087860
5  180   20 -0.006186  0.167471  0.080642
1  190   15  0.022921  0.131485  0.077203
4  180   15  0.007488  0.146624  0.077056
0  190   10  0.022921  0.121947  0.072434
3  180   10  0.002983  0.093591  0.048287
8  150   20 -0.045931  0.117772  0.035920
7  150   15 -0.054594  0.093213  0.019310
6  150   10 -0.032588  0.035051  0.001231